language: minimal
dist: trusty

addons:
  ssh_known_hosts: c4dtsrv1.epfl.ch

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      name: demo.c4dt.org
      before_deploy:
        - echo "$DEPLOY_SSH_KEY" > "$HOME/.ssh/id_ed25519"
        - head -n1 "$HOME/.ssh/id_ed25519"
        - chmod 600 "$HOME/.ssh/id_ed25519"
      deploy:
        provider: script
        script: ssh omniledger@c4dtsrv1.epfl.ch bin/update.sh
        on:
          branch: travis-keys

notifications:
  email: false
