#!/usr/bin/python3

from wsgiref.handlers import CGIHandler
from flask import Flask
from flask import request

app = Flask(__name__)


@app.route('/')
def proxyVerify():
    ticket = request.args.get('ticket')
    return """  <cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
    <cas:authenticationSuccess>
      <cas:user>{ticket}</cas:user>
      <cas:proxyGrantingTicket>{ticket}</cas:proxyGrantingTicket>
    </cas:authenticationSuccess>
  </cas:serviceResponse>""".format(ticket=ticket)

CGIHandler().run(app)

